#:import utils kivy.utils

<LoginScreen>:
    AnchorLayout:
        anchor_x: "center"
        anchor_y: "center"
        canvas.before:
            Color:
                rgba: utils.get_color_from_hex("#3AAF83")
            Rectangle:
                size: self.size
                pos: self.pos
        FloatLayout:
            canvas.before:
                Color:
                    rgba: utils.get_color_from_hex("#29986E")
                Rectangle:
                    size: dp(350), dp(450)
                    pos: root.width/2 - dp(350)/2 + dp(10), root.height/2 - dp(450)/2 - dp(10)

        FloatLayout:
            canvas.before:
                Color:
                    rgb: 1, 1, 1
                Rectangle:
                    size: dp(350), dp(450)
                    pos: root.width/2 - dp(350)/2, root.height/2 - dp(450)/2
        FloatLayout:
            Button:
                text: "LOGIN"
                font_name: "fonts/Rubik-Bold.ttf"
                font_size: dp(30)
                color: 0, 0, 0
                size_hint: None, None
                width: dp(350)
                height: dp(420)
                background_normal: ""
                background_color: 0, 0, 0, 0
                text_size: self.size
                halign: "left"
                valign: "top"
                pos: root.width/2 - dp(350)/2 + dp(40), root.height/2 - dp(450)/2
                #pos: 200, 200
            Button:
                id: login_error
                background_color: 0, 0, 0, 0
                background_normal: ""
                text: ""
                color: 1, 0, 0
                font_name: "fonts/Rubik-Regular.ttf"
                font_size: dp(14)
                size_hint: None, None
                text_size: self.size
                valign: "center"
                halign: "left"
                width: dp(270)
                height: dp(35)
                pos: root.width/2 - dp(350)/2 + dp(40), root.height/2 + dp(110)
            Button:
                text: "EMAIL"
                font_name: "fonts/Rubik-Regular.ttf"
                font_size: dp(12)
                color: 0, 0, 0
                text_size: self.size
                size_hint: None, None
                background_color: 0, 0, 0, 0
                background_normal: ""
                width: dp(350)
                height: dp(320)
                halign: "left"
                valign: "top"
                pos: root.width/2 - dp(350)/2 + dp(40), root.height/2 - dp(450)/2

            Button:
                text: "PASSWORD"
                font_name: "fonts/Rubik-Regular.ttf"
                font_size: dp(12)
                color: 0, 0, 0
                text_size: self.size
                size_hint: None, None
                background_color: 0, 0, 0, 0
                background_normal: ""
                width: dp(350)
                height: dp(240)
                halign: "left"
                valign: "top"
                pos: root.width/2 - dp(350)/2 + dp(40), root.height/2 - dp(450)/2
            TextInput:
                id: email
                background_color: utils.get_color_from_hex("#EEEEEE")
                background_normal: ""
                background_active: ""
                write_tab: False
                size_hint: None, None
                width: dp(270)
                height: dp(30)
                cursor_color: 0, 0, 0, .5
                cursor_width: dp(1)
                foreground_color: 0, 0, 0, .8
                multiline: False
                font_name: "fonts/Rubik-Regular.ttf"
                pos: root.width/2 - dp(350)/2 + dp(40), root.height/2 + dp(40)
                on_text_validate: root.validate_login(login_error, email, pwd)
            TextInput:
                id: pwd
                background_color: utils.get_color_from_hex("#EEEEEE")
                background_normal: ""
                background_active: ""
                write_tab: False
                size_hint: None, None
                width: dp(270)
                height: dp(30)
                cursor_color: 0, 0, 0, .5
                cursor_width: dp(1)
                foreground_color: 0, 0, 0, .8
                multiline: False
                font_name: "fonts/Rubik-Regular.ttf"
                password: True
                pos: root.width/2 - dp(350)/2 + dp(40), root.height/2 - dp(40)
                on_text_validate: root.validate_login(login_error, email, pwd)
            Button:
                background_color: 0, 0, 0, 0
                color: 1, 0, 0
                background_normal: ""
                text: "Reset password"
                font_name: "fonts/Rubik-Regular.ttf"
                font_size: dp(10)
                size_hint: None, None
                text_size: self.size
                halign: "center"
                valign: "center"
                width: dp(270)
                height: dp(20)
                pos: root.width/2 - dp(350)/2 + dp(40), root.height/2 - dp(65)
            Button:
                background_color: utils.get_color_from_hex("#3AAF83")
                background_normal: ""
                text: "LOGIN"
                font_name: "fonts/Rubik-Regular.ttf"
                font_size: dp(12)
                size_hint: None, None
                width: dp(270)
                height: dp(35)
                pos: root.width/2 - dp(350)/2 + dp(40), root.height/2 - dp(110)
                on_press: root.validate_login(login_error, email, pwd)
            Button:
                background_color: 0, 0, 0, 0
                background_normal: ""
                text: "Don't have an account? REGISTER HERE"
                font_name: "fonts/Rubik-Regular.ttf"
                font_size: dp(9)
                color: 0, 0, 0, .7
                size_hint: None, None
                text_size: self.size
                halign: "center"
                valign: "bottom"
                width: dp(270)
                height: dp(35)
                pos: root.width/2 - dp(350)/2 + dp(40), root.height/2 - dp(146)

<Menu>:
    Button:
        text: "back"
        size_hint: .5, .5
        pos: root.width/2 - self.width/2, root.height/2 - self.height/2
        on_press: root.manager.current = "login_screen"